// Generated by gencpp from file mutilagentsys/robotfeedbackResponse.msg
// DO NOT EDIT!


#ifndef MUTILAGENTSYS_MESSAGE_ROBOTFEEDBACKRESPONSE_H
#define MUTILAGENTSYS_MESSAGE_ROBOTFEEDBACKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mutilagentsys
{
template <class ContainerAllocator>
struct robotfeedbackResponse_
{
  typedef robotfeedbackResponse_<ContainerAllocator> Type;

  robotfeedbackResponse_()
    : taskstatus()  {
    }
  robotfeedbackResponse_(const ContainerAllocator& _alloc)
    : taskstatus(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _taskstatus_type;
  _taskstatus_type taskstatus;





  typedef boost::shared_ptr< ::mutilagentsys::robotfeedbackResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mutilagentsys::robotfeedbackResponse_<ContainerAllocator> const> ConstPtr;

}; // struct robotfeedbackResponse_

typedef ::mutilagentsys::robotfeedbackResponse_<std::allocator<void> > robotfeedbackResponse;

typedef boost::shared_ptr< ::mutilagentsys::robotfeedbackResponse > robotfeedbackResponsePtr;
typedef boost::shared_ptr< ::mutilagentsys::robotfeedbackResponse const> robotfeedbackResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mutilagentsys::robotfeedbackResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mutilagentsys::robotfeedbackResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mutilagentsys

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'mutilagentsys': ['/home/ydd/MultiAgentSystem/catkin_ws/src/mutilagentsys/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mutilagentsys::robotfeedbackResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mutilagentsys::robotfeedbackResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mutilagentsys::robotfeedbackResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mutilagentsys::robotfeedbackResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mutilagentsys::robotfeedbackResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mutilagentsys::robotfeedbackResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mutilagentsys::robotfeedbackResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f2d4e2651840b06a30204660efd416f4";
  }

  static const char* value(const ::mutilagentsys::robotfeedbackResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf2d4e2651840b06aULL;
  static const uint64_t static_value2 = 0x30204660efd416f4ULL;
};

template<class ContainerAllocator>
struct DataType< ::mutilagentsys::robotfeedbackResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mutilagentsys/robotfeedbackResponse";
  }

  static const char* value(const ::mutilagentsys::robotfeedbackResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mutilagentsys::robotfeedbackResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
string taskstatus\n\
";
  }

  static const char* value(const ::mutilagentsys::robotfeedbackResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mutilagentsys::robotfeedbackResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.taskstatus);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robotfeedbackResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mutilagentsys::robotfeedbackResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mutilagentsys::robotfeedbackResponse_<ContainerAllocator>& v)
  {
    s << indent << "taskstatus: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.taskstatus);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MUTILAGENTSYS_MESSAGE_ROBOTFEEDBACKRESPONSE_H
