// Generated by gencpp from file mutilagentsys/robotinfo.msg
// DO NOT EDIT!


#ifndef MUTILAGENTSYS_MESSAGE_ROBOTINFO_H
#define MUTILAGENTSYS_MESSAGE_ROBOTINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mutilagentsys
{
template <class ContainerAllocator>
struct robotinfo_
{
  typedef robotinfo_<ContainerAllocator> Type;

  robotinfo_()
    : robotid(0)
    , robotstatus()
    , taskid(0)  {
    }
  robotinfo_(const ContainerAllocator& _alloc)
    : robotid(0)
    , robotstatus(_alloc)
    , taskid(0)  {
  (void)_alloc;
    }



   typedef uint8_t _robotid_type;
  _robotid_type robotid;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _robotstatus_type;
  _robotstatus_type robotstatus;

   typedef uint8_t _taskid_type;
  _taskid_type taskid;





  typedef boost::shared_ptr< ::mutilagentsys::robotinfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mutilagentsys::robotinfo_<ContainerAllocator> const> ConstPtr;

}; // struct robotinfo_

typedef ::mutilagentsys::robotinfo_<std::allocator<void> > robotinfo;

typedef boost::shared_ptr< ::mutilagentsys::robotinfo > robotinfoPtr;
typedef boost::shared_ptr< ::mutilagentsys::robotinfo const> robotinfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mutilagentsys::robotinfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mutilagentsys::robotinfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mutilagentsys

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'mutilagentsys': ['/home/ydd/MultiAgentSystem/catkin_ws/src/mutilagentsys/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mutilagentsys::robotinfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mutilagentsys::robotinfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mutilagentsys::robotinfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mutilagentsys::robotinfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mutilagentsys::robotinfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mutilagentsys::robotinfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mutilagentsys::robotinfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c27b94a1a25a30817bd534d87682aca0";
  }

  static const char* value(const ::mutilagentsys::robotinfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc27b94a1a25a3081ULL;
  static const uint64_t static_value2 = 0x7bd534d87682aca0ULL;
};

template<class ContainerAllocator>
struct DataType< ::mutilagentsys::robotinfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mutilagentsys/robotinfo";
  }

  static const char* value(const ::mutilagentsys::robotinfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mutilagentsys::robotinfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 robotid\n\
string robotstatus\n\
uint8 taskid\n\
";
  }

  static const char* value(const ::mutilagentsys::robotinfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mutilagentsys::robotinfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robotid);
      stream.next(m.robotstatus);
      stream.next(m.taskid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robotinfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mutilagentsys::robotinfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mutilagentsys::robotinfo_<ContainerAllocator>& v)
  {
    s << indent << "robotid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.robotid);
    s << indent << "robotstatus: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.robotstatus);
    s << indent << "taskid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.taskid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MUTILAGENTSYS_MESSAGE_ROBOTINFO_H
