// Generated by gencpp from file mutilagentsys/robotfeedbackRequest.msg
// DO NOT EDIT!


#ifndef MUTILAGENTSYS_MESSAGE_ROBOTFEEDBACKREQUEST_H
#define MUTILAGENTSYS_MESSAGE_ROBOTFEEDBACKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mutilagentsys
{
template <class ContainerAllocator>
struct robotfeedbackRequest_
{
  typedef robotfeedbackRequest_<ContainerAllocator> Type;

  robotfeedbackRequest_()
    : taskid(0)  {
    }
  robotfeedbackRequest_(const ContainerAllocator& _alloc)
    : taskid(0)  {
  (void)_alloc;
    }



   typedef int64_t _taskid_type;
  _taskid_type taskid;





  typedef boost::shared_ptr< ::mutilagentsys::robotfeedbackRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mutilagentsys::robotfeedbackRequest_<ContainerAllocator> const> ConstPtr;

}; // struct robotfeedbackRequest_

typedef ::mutilagentsys::robotfeedbackRequest_<std::allocator<void> > robotfeedbackRequest;

typedef boost::shared_ptr< ::mutilagentsys::robotfeedbackRequest > robotfeedbackRequestPtr;
typedef boost::shared_ptr< ::mutilagentsys::robotfeedbackRequest const> robotfeedbackRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mutilagentsys::robotfeedbackRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mutilagentsys::robotfeedbackRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mutilagentsys

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'mutilagentsys': ['/home/ydd/multiagent/catkin_ws/src/mutilagentsys/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mutilagentsys::robotfeedbackRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mutilagentsys::robotfeedbackRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mutilagentsys::robotfeedbackRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mutilagentsys::robotfeedbackRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mutilagentsys::robotfeedbackRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mutilagentsys::robotfeedbackRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mutilagentsys::robotfeedbackRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a394ac3cfcfa8145ba953019a6f01f2e";
  }

  static const char* value(const ::mutilagentsys::robotfeedbackRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa394ac3cfcfa8145ULL;
  static const uint64_t static_value2 = 0xba953019a6f01f2eULL;
};

template<class ContainerAllocator>
struct DataType< ::mutilagentsys::robotfeedbackRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mutilagentsys/robotfeedbackRequest";
  }

  static const char* value(const ::mutilagentsys::robotfeedbackRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mutilagentsys::robotfeedbackRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 taskid\n\
\n\
";
  }

  static const char* value(const ::mutilagentsys::robotfeedbackRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mutilagentsys::robotfeedbackRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.taskid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robotfeedbackRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mutilagentsys::robotfeedbackRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mutilagentsys::robotfeedbackRequest_<ContainerAllocator>& v)
  {
    s << indent << "taskid: ";
    Printer<int64_t>::stream(s, indent + "  ", v.taskid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MUTILAGENTSYS_MESSAGE_ROBOTFEEDBACKREQUEST_H
