// Generated by gencpp from file mutilagentsys/robotfeedback.msg
// DO NOT EDIT!


#ifndef MUTILAGENTSYS_MESSAGE_ROBOTFEEDBACK_H
#define MUTILAGENTSYS_MESSAGE_ROBOTFEEDBACK_H

#include <ros/service_traits.h>


#include <mutilagentsys/robotfeedbackRequest.h>
#include <mutilagentsys/robotfeedbackResponse.h>


namespace mutilagentsys
{

struct robotfeedback
{

typedef robotfeedbackRequest Request;
typedef robotfeedbackResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robotfeedback
} // namespace mutilagentsys


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mutilagentsys::robotfeedback > {
  static const char* value()
  {
    return "7776dd36f3d35e00906447aeb823d4a1";
  }

  static const char* value(const ::mutilagentsys::robotfeedback&) { return value(); }
};

template<>
struct DataType< ::mutilagentsys::robotfeedback > {
  static const char* value()
  {
    return "mutilagentsys/robotfeedback";
  }

  static const char* value(const ::mutilagentsys::robotfeedback&) { return value(); }
};


// service_traits::MD5Sum< ::mutilagentsys::robotfeedbackRequest> should match 
// service_traits::MD5Sum< ::mutilagentsys::robotfeedback > 
template<>
struct MD5Sum< ::mutilagentsys::robotfeedbackRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mutilagentsys::robotfeedback >::value();
  }
  static const char* value(const ::mutilagentsys::robotfeedbackRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mutilagentsys::robotfeedbackRequest> should match 
// service_traits::DataType< ::mutilagentsys::robotfeedback > 
template<>
struct DataType< ::mutilagentsys::robotfeedbackRequest>
{
  static const char* value()
  {
    return DataType< ::mutilagentsys::robotfeedback >::value();
  }
  static const char* value(const ::mutilagentsys::robotfeedbackRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mutilagentsys::robotfeedbackResponse> should match 
// service_traits::MD5Sum< ::mutilagentsys::robotfeedback > 
template<>
struct MD5Sum< ::mutilagentsys::robotfeedbackResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mutilagentsys::robotfeedback >::value();
  }
  static const char* value(const ::mutilagentsys::robotfeedbackResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mutilagentsys::robotfeedbackResponse> should match 
// service_traits::DataType< ::mutilagentsys::robotfeedback > 
template<>
struct DataType< ::mutilagentsys::robotfeedbackResponse>
{
  static const char* value()
  {
    return DataType< ::mutilagentsys::robotfeedback >::value();
  }
  static const char* value(const ::mutilagentsys::robotfeedbackResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MUTILAGENTSYS_MESSAGE_ROBOTFEEDBACK_H
